### ISSUE TITLE
`DragBox` cannot show when selecting

### ISSUE THREAD

**Issue by HanwGeek** [openlayers/openlayers#11784]
**Describe the bug**
I defined a `DragBox` in `Vue` with `Openlayers` . But when I start to use it to select, it doesn't show on the screen but there are some features selected indeed. How can I make the dragbox show on the screen when selecting features? Thanks!

**To Reproduce**
```javascript
      this.dragBox = new DragBox({
        condition: platformModifierKeyOnly,
        style: new Style({
          stroke: new Stroke({
            color: [0, 0, 255, 1],
          }),
        }),
      })
      this.map.addInteraction(this.dragBox)
```
```css
<style scoped>
.ol-dragbox {
  background-color: rgba(255, 255, 255, 0.4);
  border-color: rgba(100, 150, 0, 1);
}
</style>
```
**Expected behavior**
Show dragbox on screen when selecting.
