### ISSUE TITLE
[accessibility] Can the 'Accessible Map' apply by default?

### ISSUE THREAD

**Issue by Malvoz** [openlayers/openlayers#12309]
[Many popular web maps are keyboard focusable by default](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/examples/create-map.html), it'd be an accessibility improvement to all OpenLayers maps if the [Accessible Map](https://openlayers.org/en/latest/examples/accessible.html) was the default (the keyboard focusability aspect of it at least, perhaps not the "skip link" component (https://github.com/openlayers/openlayers/issues/12310)).

If it is deemed annoying that the focus outline is showing for all users it can be changed to only be visible when the user is using a keyboard:

```css
.map:focus:not(:focus-visible) { /* https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible */
  outline: 0;
}
```
