### ISSUE TITLE
Change text colour for scaleLine

### ISSUE THREAD

**Issue by Gdanycz** [openlayers/openlayers#16255]
I can't change the text color of the scaleLine, every time I change it and move in the map, it redraws and I have the default color again. How can I solve this?

My style
![image](https://github.com/user-attachments/assets/b154fa75-e86b-4fa2-a7a4-d2f60cd02765)

OL style - after move on map
![image](https://github.com/user-attachments/assets/d430ea4c-c665-4e9f-8511-02b5efebd0cb)

**Comment by mike-000** [comment]
Set it using css, for example

      .ol-scale-text {
        color: #800000;
      }
      .ol-scale-step-text {
        color: #008000;
      }

https://stackblitz.com/edit/js-wbl4m8?file=package.json,index.js,index.html

**Comment by Gdanycz** [comment]
Fixed with this code:
```css
.ol-scale-text {
  color: rgb(255, 255, 255); 
  mix-blend-mode: difference;
  text-shadow: none;
}

.ol-scale-step-text {
  color: rgb(255, 255, 255); 
  mix-blend-mode: difference;
  text-shadow: none;
}
```
